Fix some tests ("mkcmake configure" does not support parallel execution)

diff --git a/tests/test_subprj_dash/Makefile b/tests/test_subprj_dash/Makefile
--- a/tests/test_subprj_dash/Makefile
+++ b/tests/test_subprj_dash/Makefile
@@ -8,8 +8,10 @@ test:
 	${MAKE} ${MAKEFLAGS} -f ${.CURDIR}/test.mk all 2>&1 | \
 	sed 's,n*b*make\[[0-9]*\],bmake,' | \
 	mkc_test_helper "${PREFIX}" "${.OBJDIR}" > $$tmp_out; \
-	diff ${.CURDIR}/expect.out $$tmp_out && \
-	echo '      succeeded' 1>&2 || \
-	{ echo '      FAILED' 1>&2; false; }
+	if diff -u10 ${.CURDIR}/expect.out $$tmp_out; then \
+		echo '      succeeded' 1>&2; \
+	else \
+		echo '      FAILED' 1>&2; false; \
+	fi
 
 .include <mkc.subprj.mk>
